export function getBulkProgressCopy(type) {
  const map = {
    social: {
      status: 'Visiting each website to find emails and social links...',
      ringLabel: 'websites checked',
      leftTitle: 'Websites checked',
      leftSub: (done, total) => `${done} of ${total} done`,
      rightTitle: 'Leads with results',
      rightSub: 'Found at least one email or social link',
      failNote: 'websites could not be read',
      bottomTitle: 'Emails & social links collected',
      bottomUnit: 'items',
      etaPerItem: 5,
    },
    city: {
      status: 'Reading Google Maps links to detect cities...',
      ringLabel: 'leads reviewed',
      leftTitle: 'Leads reviewed',
      leftSub: (done, total) => `${done} of ${total} done`,
      rightTitle: 'Cities found',
      rightSub: 'City saved on the lead',
      failNote: 'leads had no city detected',
      bottomTitle: 'Cities saved',
      bottomUnit: 'cities',
      etaPerItem: 2,
    },
    whatsapp: {
      status: 'Checking which numbers are on WhatsApp...',
      ringLabel: 'numbers checked',
      leftTitle: 'Numbers checked',
      leftSub: (done, total) => `${done} of ${total} done`,
      rightTitle: 'Checks completed',
      rightSub: 'WhatsApp responded to the check',
      failNote: 'checks failed',
      bottomTitle: 'Successful checks',
      bottomUnit: 'numbers',
      etaPerItem: 3,
    },
    ads: {
      status: 'Checking each website for running ads...',
      ringLabel: 'sites analyzed',
      leftTitle: 'Sites analyzed',
      leftSub: (done, total) => `${done} of ${total} done`,
      rightTitle: 'Running ads',
      rightSub: 'Sites with active ads detected',
      failNote: 'sites with no ads',
      bottomTitle: 'Sites running ads',
      bottomUnit: 'sites',
      etaPerItem: 4,
    },
    mail: {
      status: 'Looking up email addresses for each domain...',
      ringLabel: 'domains checked',
      leftTitle: 'Domains checked',
      leftSub: (done, total) => `${done} of ${total} done`,
      rightTitle: 'Emails found',
      rightSub: 'At least one email captured',
      failNote: 'domains with no email',
      bottomTitle: 'Email addresses found',
      bottomUnit: 'emails',
      etaPerItem: 5,
    },
  };
  return map[type] || map.social;
}
